# Generated by Django 5.2.5 on 2025-08-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Get In Touch", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="I'm currently available for freelance work and interesting projects. Feel free to reach out!"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="surajkumar.sm09@gmail.com", max_length=254
                    ),
                ),
                (
                    "address",
                    models.CharField(default="Lucknow, Mohanlalganj", max_length=255),
                ),
            ],
        ),
    ]
