# Generated by Django 5.2.5 on 2025-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contactinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("codepen", "CodePen"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("leetcode", "Leetcode"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class (e.g., fab fa-github)",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="herosection",
            name="title",
            field=models.CharField(default="Suraj", max_length=200),
        ),
    ]
