# Generated by Django 5.2.5 on 2025-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sociallink_alter_herosection_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon_class",
            field=models.CharField(help_text="e.g., fab fa-github", max_length=100),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("twitter", "Twitter/X"),
                    ("codepen", "CodePen"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                ],
                max_length=50,
            ),
        ),
    ]
